# Use postgres/example user/password credentials
version: '3.1'

services:
  
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - postgres
 
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432 
 