# Use an official Node.js runtime as the base image
FROM node:17

# Set the working directory within the container
WORKDIR /Project

# Copy your API source code into the container
COPY . .

# Install dependencies
RUN npm install

# Expose the port your API will run on
EXPOSE 4000

# Define the command to start your API
CMD ["npm", "start"]